### ISSUE TITLE
any updates or alternative here?

### ISSUE THREAD

**Issue by alekksander** [dmacvicar/kopete-facebook#5]

**Comment by dmacvicar** [comment]
Sorry, I don't understand your question?

Is there anything that the first lines of the README does not answer?

**Comment by alekksander** [comment]
was just hoping that it might get renewed one day, or You know any alternative. seems there is not. pls close :)

**Comment by dmacvicar** [comment]
I am not sure if the plugin is working because I am not using it. Have you tried to build it on any distro? May be it still works.

If it does not, https://github.com/dequis/purple-facebook should be an alternative, for Pidgin, and also a good source to fix this one (in case it needs to).
